import type { Metadata } from 'next';
import { M_PLUS_Rounded_1c, Roboto } from 'next/font/google';
import './globals.css';
import { ThemeProvider, createTheme } from '@mui/material';
import MuiThemeProvider from './mui-theme.provider';

const roboto = Roboto({
  weight: ['400', '500', '700', '900'],
  subsets: ['latin'],
  style: ['normal'],
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='pt-br'>
      <body className={`${roboto.variable} font-sans`}>
        <MuiThemeProvider>{children}</MuiThemeProvider>
      </body>
    </html>
  );
}
